import{a as b,i as n,S as L}from"./assets/vendor-DtRopbQG.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const p=async s=>{try{const o=await b.get(`https://pixabay.com/api/?page=${c}&per_page=${f}`,{params:{key:"49409853-9b66959f7621caabc2c0e0f94",q:s.trim(),image_type:"photo",orientation:"horizontal",safesearch:!0}});return{images:o.data.hits,totalHits:o.data.totalHits}}catch(o){throw console.log(o),n.error({title:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:5e3}),o}},g=document.querySelector(".gallery"),y=s=>{const o=s.map(({largeImageURL:r,webformatURL:i,tags:e,likes:t,views:a,comments:h,downloads:v})=>`
  <li class="gallery-item">
    <a class="gallery-item" href="${r}">
      <div class="photo-card">
        <img src="${i}" alt="${e}" />
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${a}</p>
          <p><b>Comments:</b> ${h}</p>
          <p><b>Downloads:</b> ${v}</p>
        </div>
      </div>
    </a>
  </li>`).join("");g.innerHTML=o,R.refresh()},R=new L(".gallery a");function w(){g.innerHTML=""}const m=document.querySelector(".form"),d=document.querySelector(".loader"),l=document.querySelector(".input"),u=document.querySelector(".more-btn"),S=document.querySelector(".gallery-item");m.addEventListener("submit",s=>{if(s.preventDefault(),l.value.trim()===""){n.warning({title:"Please type what you want to find",position:"topRight",timeout:5e3});return}w(),o(),e(),p(l.value).then(t=>{if(r(),t.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),e(),m.reset();return}y(t),i()}).catch(t=>{console.log(t),r(),n.error({title:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:5e3})});function o(){d.classList.add("active")}function r(){d.classList.remove("active")}function i(){u.classList.add("active")}function e(){u.classList.remove("active")}});let c=1;const f=15;u.addEventListener("click",async()=>{const s=Math.ceil(totalHits/f);c>s&&(moreClassRemove(),classRemove(),n.error({title:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:5e3})),classRemove(),moreClassRemove();try{const r=await p(l.value);y(r),c+=1,c>1&&moreClassAdd()}catch(r){console.log(r)}const o=S.getBoundingClientRect();window.scrollBy(0,o*2)});
//# sourceMappingURL=index.js.map
